export const livres = [
  {
    id: 1,
    titre: "Scrum pour les tous-petits",
    nombre_pages: 25,
    extrait: "https://www.scrum.org/scrumGuide",
    resume: "Le guide Scrum pour enfant dès six ans",
    annee_edition: 2024,
    utilisateur: 1,
    categorie: 1,
    editeur: 1,
    ecrivain: 1,
    image: "1.png",
  },
  {
    id: 2,
    titre: "The Scrum Guide",
    nombre_pages: 13,
    extrait: "https://www.scrum.org/scrumGuideBaby",
    resume: "Le guide Scrum",
    annee_edition: 2020,
    utilisateur: 2,
    categorie: 1,
    editeur: 2,
    ecrivain: 2,
    image: "1.png",
  },
  {
    id: 3,
    titre: "JavaScript Moderne",
    nombre_pages: 350,
    extrait: "https://www.example.com/js-moderne",
    resume: "Un guide pour maîtriser JavaScript",
    annee_edition: 2022,
    utilisateur: 3,
    categorie: 1,
    editeur: 3,
    ecrivain: 3,
    image: "1.png",
  },
  {
    id: 4,
    titre: "React en Action",
    nombre_pages: 280,
    extrait: "https://www.example.com/react-action",
    resume: "Apprenez React avec des exemples concrets",
    annee_edition: 2023,
    utilisateur: 4,
    categorie: 3,
    editeur: 4,
    ecrivain: 4,
    image: "1.png",
  },
  {
    id: 5,
    titre: "L'Art de la Guerre",
    nombre_pages: 250,
    extrait: "https://www.example.com/art-guerre",
    resume: "Un traité militaire classique",
    annee_edition: 500,
    utilisateur: 5,
    categorie: 4,
    editeur: 5,
    ecrivain: 5,
    image: "1.png",
  },
  {
    id: 6,
    titre: "Python pour les nuls",
    nombre_pages: 420,
    extrait: "https://www.example.com/python-nuls",
    resume: "Un livre pour débuter avec Python",
    annee_edition: 2021,
    utilisateur: 6,
    categorie: 5,
    editeur: 6,
    ecrivain: 6,
    image: "1.png",
  },
  {
    id: 7,
    titre: "La Blockchain expliquée",
    nombre_pages: 300,
    extrait: "https://www.example.com/blockchain",
    resume: "Comprendre la technologie blockchain",
    annee_edition: 2020,
    utilisateur: 7,
    categorie: 6,
    editeur: 7,
    ecrivain: 7,
    image: "1.png",
  },
  {
    id: 8,
    titre: "Design UX/UI",
    nombre_pages: 350,
    extrait: "https://www.example.com/design-uxui",
    resume: "Les bases de l'expérience utilisateur",
    annee_edition: 2023,
    utilisateur: 8,
    categorie: 7,
    editeur: 8,
    ecrivain: 8,
    image: "1.png",
  },
  {
    id: 9,
    titre: "Les bases du DevOps",
    nombre_pages: 275,
    extrait: "https://www.example.com/devops",
    resume: "Introduction aux concepts DevOps",
    annee_edition: 2022,
    utilisateur: 9,
    categorie: 8,
    editeur: 9,
    ecrivain: 9,
    image: "1.png",
  },
  {
    id: 10,
    titre: "L'intelligence artificielle pour débutants",
    nombre_pages: 320,
    extrait: "https://www.example.com/ia-debutants",
    resume: "Un guide accessible à l'IA",
    annee_edition: 2024,
    utilisateur: 10,
    categorie: 9,
    editeur: 10,
    ecrivain: 10,
    image: "1.png",
  },
  {
    id: 11,
    titre: "Big Data et Analyse de Données",
    nombre_pages: 400,
    extrait: "https://www.example.com/bigdata",
    resume: "Comprendre et exploiter les données massives",
    annee_edition: 2021,
    utilisateur: 11,
    categorie: 10,
    editeur: 11,
    ecrivain: 11,
    image: "1.png",
  },
  {
    id: 12,
    titre: "Cybersécurité pour tous",
    nombre_pages: 380,
    extrait: "https://www.example.com/cybersecurite",
    resume: "Protégez vos données et votre vie privée",
    annee_edition: 2023,
    utilisateur: 12,
    categorie: 11,
    editeur: 12,
    ecrivain: 12,
    image: "1.png",
  },
];
